### ISSUE TITLE
Error on case sensitive DBMS

### ISSUE THREAD

**Issue by gabrielrosset** [mikasmart/moodle-report_benchmark#12]
Commit below give a small fix for case sensitive DBMS
Actually when you are using a case sensitive DBMS an error is thrown because 'path' and 'depth' fields are in upper case in SQL request.

This commit fix this : 
https://github.com/mikasmart/benchmark/pull/11/commits/63f8c8202e735414337da11c2e568656945432f2

**Comment by gabrielrosset** [comment]
There is the same mistake at line 271.
Prefer the commit below which make a full fix for this issue : 
https://github.com/mikasmart/benchmark/pull/13/commits/063d7392e45ec08bc563e290de4665f2c6ceb28d

**Comment by mikasmart** [comment]
Fixed in 1.0.3.

Thanks Gabriel !
