### ISSUE TITLE
Add more FS tests

### ISSUE THREAD

**Issue by tmuras** [mikasmart/moodle-report_benchmark#14]
Thank you for the nice plugin.
I'd be nice to add more tests of the filesystem. The issues may be not just with file read & write but also with:
* speed of listing a directory content (e.g. create directory with 1000 files and list it)
* speed of listing file/directory attributes

**Comment by martignoni** [comment]
@tmuras Still interested to contribute? Would be glad to get some new tests.

**Comment by martignoni** [comment]
@mikasmart Don't you think this would be a good idea?

**Comment by mikasmart** [comment]
This is not really an issue and the contributor hasn't reacted for a long time.
