### ISSUE TITLE
Languages (and documentation page)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [mikasmart/moodle-report_benchmark#15]
Hi,
I love your plugin.

Currently there is no need to host language strings for languages other than English inside the lang folder of your plugin, as all languages tranlations is currently done in AMOS. Please see https://lang.moodle.org/mod/forum/discuss.php?d=2485 

I am the maintainer for the es_mx language pack and I have already uploaded the Mexican Spanish strings for this plugin :)

You can safely:

- Remove the fr language folder for this plugin in GitHub (and the Moodle plugins database), as fr language strings for this plugin are already hosted in AMOS and they have precedence over the strings inside the ZIP file for the plugin.

- Change the roadmap here in GitHub where it states "Add more language", as it is being actively done :) .

I hope you don't mind that I want to create a Moodle Docs page for this plugin. Once a Moodle Docs page for this plugin is created, it will be very easy to add links to Docs translations in other languages; I will make the es Docs page. 
For the intended Moodle Docs page, I will copy some text and images from this GitHub page and the Moodle french forum posts. I expect to have the Moodle Docs page finished by this coming weekend.

Thanks for a very nice and useful Moodle plugin. 
Now I have the objective data to ask my Dean for more $ for our over-worked, under-powered, aging, Moodle servers :)

**Comment by mikasmart** [comment]
Thanks "germanvaleroelizondo" :)

Can you contact me at m.pannequin[at]xperteam.fr to talk about this, i need more informations in private.

Have a nice day !
