### ISSUE TITLE
Rename plugin repository

### ISSUE THREAD

**Issue by martignoni** [mikasmart/moodle-report_benchmark#20]
Rename plugin repository to follow [naming scheme recommended by Moodle HQ](https://docs.moodle.org/dev/Plugin_contribution#Repository).

**Comment by martignoni** [comment]
This should be, following above recommendation:

`moodle-report_benchmark`

**Comment by martignoni** [comment]
@mikasmart or @lenacus: can you do this?

**Comment by mikasmart** [comment]
Tu confirmes pour **mikasmart/benchmark** vers **mikasmart/moodle-report_benchmark** ?

**Comment by martignoni** [comment]
Yes, je confirme :-)

**Comment by mikasmart** [comment]
Voilà c'est fait, je te laisse modifier le contenu (readme par exemple) pour refaire les liens ci nécessaire.

**Comment by martignoni** [comment]
Will do.
