### ISSUE TITLE
Improve the Reading/Writing file performance documentation

### ISSUE THREAD

**Issue by luisdev** [mikasmart/moodle-report_benchmark#25]
I installed and ran the /report/benchmark/index.php report on my Moodle test server. The results were shocking!

The **Reading file performance** result was 3.900 vs the acceptable limit of 0.5.
The **Writing file performance** result was an even worse 81.238 vs the acceptable limit of 1!

So there's clearly something wrong in my dev environment...

The text below those **Reading file performance** and **Writing file performance** sections says: 
"Read/Write a file multiple times to check the reading speed of the Moodle temporary folder".
That doesn't help me very much.

The "Moodle Docs for this page" points to an empty page (http://docs.moodle.org/37/en/admin/report/benchmark/index).

There doesn't seem to be anything on the https://github.com/mikasmart/moodle-report_benchmark/wiki page either.

Please add some documentation that explains what this "Moodle temporary folder" is and how it should be setup. Is it a folder that needs to be configured in Moodle? Or is it a PHP setting?

How must that temp folder be configured? Especially if you are running a large multi-node / load-balanced Moodle environment. Should this "Moodle temporary folder" be on each server node? Or should it be in the shared Moodledata folder?

At the very least, the report_benchmark documentation could point to an article in MoodleDocs that explains the meaning and setup of these settings.

**Comment by Lenacus** [comment]
Hello Luis,

which version do you use of the plugin?

Thank you for the report of dead links, we will do what is necessary.

**Comment by luisdev** [comment]
It is version v1.3.0 - 2019083101

**Comment by Lenacus** [comment]
Ok it's the last version.

Try this : [https://moodle.org/mod/forum/discuss.php?d=335357#p1359598](url)
or this : [https://moodle.org/mod/forum/discuss.php?d=335066](url)

I suspect a security or a slow disk, it's a classic problem . Try to change your tempory directory in memory.

**Comment by luisdev** [comment]
What do you mean by "change your tempory directory in memory"? Which temporary directory?
Is that a php.ini setting? A OS setting? A web server setting?

The documentation needs to describe the setup clearly, with no assumptions.

**Comment by martignoni** [comment]
@luisdev: Making the temp directory on a ramfs device is a server OS setting and has nothing to do with this plugin setting. It was just a (kind) advice to try and improve your read/write performance on your server.

> Please add some documentation that explains what this "Moodle temporary folder" is and how it should be setup. Is it a folder that needs to be configured in Moodle? Or is it a PHP setting?
> 
> How must that temp folder be configured? Especially if you are running a large multi-node / load-balanced Moodle environment. Should this "Moodle temporary folder" be on each server node? Or should it be in the shared Moodledata folder?

Your questions are not about Benchmark, but about how to improve your Moodle server performance. Benchmark is just a tool to point to the problematic areas. I'll suggest you have a look at https://docs.moodle.org/37/en/Performance_recommendations. Also, you'll get more help on this subject on the [Hardware and Performance forum](https://moodle.org/mod/forum/view.php?id=596) on moodle.org.

> At the very least, the report_benchmark documentation could point to an article in MoodleDocs that explains the meaning and setup of these settings.

Good idea. See #26.

**Comment by luisdev** [comment]
The issue I had is that the current Benchmark **documentation** says: "change your temporary directory in memory"? But it doesn't say WHICH temporary directory. Is it a directory setting in php.ini ? A directory setting in the OS? A directory setting in the web server?

The problem is the documentation. The current "change your tempory directory in memory" instruction in the documentation is too vague.

**Comment by martignoni** [comment]
Please indicate your suggestion of modification in #26, so that we can include it in a future version.

**Comment by luisdev** [comment]
My suggestion for modification is to enhance and explain what the "change your temporary directory in memory" part of the documentation means. Which directory is it? Something in php.ini? If not, where?

**Comment by plindgreen** [comment]
I too was wondering what to do about that warning. I saw a reference to what appears to be a moodle temp folder here:
https://scholarlms.net/performance-recommendations/
'/tempdir/'  => '/var/www/moodle/temp',     // for custom $CFG->tempdir locations**'/tempdir/'  => '/var/www/moodle/temp',     // for custom $CFG->tempdir locations**
and while browsing the moodle installation I see a 'temp' folder in our moodle data folder.

I get the impression this moodle data temp folder should be set to a memory location (ie a 'Ram Disk') (in config.php, ie in Windows r:\MoodleRamDisk\) instead of our hard disk, ? ie http://woshub.com/create-ram-disk-windows-server/

**Comment by luisdev** [comment]
> 
> I get the impression this moodle data temp folder should be set to a memory location (ie a 'Ram Disk') (in config.php, ie in Windows r:\MoodleRamDisk) instead of our hard disk, ? ie http://woshub.com/create-ram-disk-windows-server/

I know this issue is closed, but just adding a response to the above message:
A Ram Disk is not persistent, so I don't think it's suitable for this. The $CFG->tempdir and other settings will be lost when the server is restarted.
