### ISSUE TITLE
Add link to Moodle performance documentation

### ISSUE THREAD

**Issue by martignoni** [mikasmart/moodle-report_benchmark#26]
See #25.

**Comment by luisdev** [comment]
See comments in https://github.com/mikasmart/moodle-report_benchmark/issues/25

**Comment by luisdev** [comment]
As per #25 my suggestion for modification is to enhance and explain what the "change your temporary directory in memory" part of the documentation means. Which directory is it? Something in php.ini? If not, where?

**Comment by luisdev** [comment]
I don't think the changes made in this commit explain what the meaning of what "change your temporary directory in memory" is.
Please can you clarify that part of the instructions are. Its should explain what the "temporary directory" is.
