### ISSUE TITLE
Purge the Moodle cache link fails

### ISSUE THREAD

**Issue by jderriks** [mikasmart/moodle-report_benchmark#32]
![afbeelding](https://user-images.githubusercontent.com/1659604/95990606-0890f680-0e2c-11eb-8484-2acef176591d.png)

The purge the moodle cache link points to admin/purgecaches.php but that URL seems invalid.

**Comment by Lenacus** [comment]
Hi, what's the moodle version ?

**Comment by jderriks** [comment]
Ah I see it should work fine as long as the moodle folder is in the base URL of the domain. So if moodle's base URL is on  xyz.com it works fine but I have some test sites on xyz.com/testmoodle1 and xyz.com/testmoodle2 and then the benchmark will not add the testmoodle[12] folder in the path to the purgecaches.php file.

**Comment by ralf-krause** [comment]
The url is still invalid. 

Yes, I know that my Moodle is not in the root folder of the web server. The url should be read from the Moodle config.php. Then the urls will work with every Moodle platform.

**Comment by martignoni** [comment]
Please try this version: https://github.com/mikasmart/moodle-report_benchmark/tree/32-purge-cache-link and report here.

Don't forget to purge the lang cache after installing. The fix is only valid in English.

**Comment by ralf-krause** [comment]
I download the zip and install it. There is no database update. Okay, I purge the caches and switch to English. Then I run the benchmark test. I need a lot of attempts to get the url. No, the url does not work. It's the same url as before ... you can see it in the bottom line of the browser.

The url of the web site is https://bildungsportal.magdeburg.de/moodle/

<img width="1198" alt="bildungsportal-benchmark" src="https://user-images.githubusercontent.com/27956839/212952473-cb157d36-535b-4d2c-9ca9-0155d8c5945b.png">

**Comment by martignoni** [comment]
~~How did you download a zip of this modification? I think it's not possible to download a zip from a branch. Are you sure you've downloaded the correct branch?~~

Just saw that clicking on ZIP downloads the selected branch. Sorry for the noise. 

I'll check how to make the link relative.

**Comment by ralf-krause** [comment]
I follow your link https://github.com/mikasmart/moodle-report_benchmark/tree/32-purge-cache-link
There I click on the button "code" and then on "Download zip". 
The name of the zip is moodle-report_benchmark-32-purge-cache-link.zip ... this seems to be the correct branch.

And this is the string from the web server 
`$string['slowwebsolution'] = '<ul><li><a href="{$a}" target="_blank">Purge the Moodle cache</a>.</li></ul>';
`

**Comment by martignoni** [comment]
Please give it another try with the last version of branch: https://github.com/mikasmart/moodle-report_benchmark/tree/32-purge-cache-link

**Comment by ralf-krause** [comment]
Now it seems to be correct. I do the same as before ... install the new plugin version, the user account runs in English and I purge the caches. It works. The link is okay and shows the website in the subfolder. 

We have a lot of Moodle platforms on the Bildungsserver Sachsen-Anhalt ... look at the link for every school https://moodle.bildung-lsa.de


<img width="1025" alt="bildungsportal-benchmark-2" src="https://user-images.githubusercontent.com/27956839/212980646-a38439fb-681a-40cc-a5c3-acc48cc27270.png">

**Comment by martignoni** [comment]
Lots of platforms indeed. Thanks for the test.

**Comment by ralf-krause** [comment]
With the plugin update to Benchmark Test 1.5.0 I get the same error again. The url for "Purge the Moodle cache" does not contain the subfolder "moodle". See the bottom line of the screenshot.

<img width="1160" alt="Benchmark test 1.5.0" src="https://user-images.githubusercontent.com/27956839/213691042-3ab2d2ac-c7a2-4c27-8678-7967af486168.png">

**Comment by martignoni** [comment]
Can you confirm the string was correctly updated in the german lang pack?

**Comment by ralf-krause** [comment]
Hi Nicolas, the string is not changed in the AMOS translator. There is still the old englisch text so I should not change the german text.

In AMOS
```
$string['slowwebsolution'] ='<ul><li><a href="/admin/purgecaches.php" target="_blank">Purge the Moodle cache</a> </li></ul>';
$string['slowwebsolution'] ='<ul><li><a href="/admin/purgecaches.php" target="_blank">Leeren Sie den Moodle-Cache</a>.</li></ul>';
```

In the plugin language file
```
$string['slowwebsolution'] = '<ul><li><a href="{$a}" target="_blank">Purge the Moodle cache</a>.</li></ul>';
```

**Comment by martignoni** [comment]
A AMOS bug? The plugin code has the new string, so AMOS should have the new string.

Humbly suggesting you update it according the plugin code.

**Comment by ralf-krause** [comment]
I just set the string in the german AMOS translation. We must wait some time to get the sting in the language pack.
```
$string['slowwebsolution'] = '<ul><li><a href="{$a}" target="_blank">Leeren Sie den Moodle-Cache.</a></li></ul>';
```

It seems to be a bug in AMOS. Yes, I translated two new strings and they are already on our platform. But the changed string can not be found in AMOS.

<img width="978" alt="Benchmark test with new test" src="https://user-images.githubusercontent.com/27956839/213729363-c8e5b9c9-170a-4792-ad1a-75c8d323dcf0.png">

**Comment by ralf-krause** [comment]
Please look at https://lang.moodle.org/mod/forum/discuss.php?d=8785#p10323

**Comment by ralf-krause** [comment]
The new English text for deleting the caches is not in AMOS two weeks after the change. This prevents the correct link from becoming available in English and other languages. The German text is correct, but only because I was there during the revision.

![B33A9567-E0BA-4CEF-9833-DCE5A2A4D2C5](https://user-images.githubusercontent.com/27956839/215984273-c34394e7-ff9f-4b79-8498-05d88bf9a710.png)

**Comment by martignoni** [comment]
The link is OK in English when using the plugin, since its strings aren't pulled from AMOS, but directly from the plugin source code.

David Mudrak is working on this AMOS bug. We've just to wait for a fix (see here: https://lang.moodle.org/mod/forum/discuss.php?d=8785).

**Comment by ralf-krause** [comment]
My idea was that someone wants to translate the Benchmark strings to Italian. Then you get the wrong English text. Yes, I saw that German and French are using something different from the English text. Yes, I can wait :-)

![benchmark-purge-caches-it](https://user-images.githubusercontent.com/27956839/216059535-39f09856-1670-43bd-af60-12c98fef8068.png)

**Comment by martignoni** [comment]
👍
