### ISSUE TITLE
Hello I have a problems and i dont know where is.. Can somebody help me

### ISSUE THREAD

**Issue by Jocruzram** [mikasmart/moodle-report_benchmark#34]
![d](https://user-images.githubusercontent.com/74392984/99188874-9c5c2800-2734-11eb-9dbc-a6cf6d924075.png)
![a](https://user-images.githubusercontent.com/74392984/99188876-9cf4be80-2734-11eb-9ff4-d4c253d0cd51.png)
![b](https://user-images.githubusercontent.com/74392984/99188877-9d8d5500-2734-11eb-93ca-82a0dbf3ef82.png)
![c](https://user-images.githubusercontent.com/74392984/99188878-9d8d5500-2734-11eb-8f27-ea57134eeade.png)

**Comment by martignoni** [comment]
I'm afraid it's not possible to give you help without knowing you very server setup. You should check with your server provider.

Have a look at Moodle performance documentation: https://docs.moodle.org/310/en/Performance_recommendations. Also, you'll get more help on this subject on the Hardware and Performance forum on https://moodle.org.
