### ISSUE TITLE
hard-linked path in lang file

### ISSUE THREAD

**Issue by ndunand** [mikasmart/moodle-report_benchmark#35]
https://github.com/mikasmart/moodle-report_benchmark/blob/852aa6471a579f805c1726eb53e4f003bb0dd478/lang/en/report_benchmark.php#L100

This URL should be built using a moodle_url constructor and not hard-coded in a lang file. At least, to ensure portability, it should use a relative path, e.g. `../../admin/etc.`

**Comment by martignoni** [comment]
A moodle_url constructor is not adequate here. Will fix the string with a relative path.
